spring:
  application:
    name: energy-market-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:55432/energy_market}
    username: ${DB_USER:energy_market}
    password: ${DB_PASSWORD:energy_market}
  flyway:
    enabled: true

market:
  feed:
    url: ${USEP_FEED_URL:https://nems.sn.sg/api/status.json}
    enabled: ${USEP_POLLING_ENABLED:true}
    cron: ${USEP_POLL_CRON:0 2,32 * * * *}
    connect-timeout: 3s
    read-timeout: 5s
    stale-after: 40m

management:
  endpoints:
    web:
      exposure:
        include: health,info
