spring:
  application:
    name: energy-market-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:55432/energy_market}
    username: ${DB_USER:energy_market}
    password: ${DB_PASSWORD:energy_market}
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
