-- F4 (CSDT4-19, CSDT4-20): shifting suggestions and the resident's decisions on them.
-- Money is SGD per run (NUMERIC), prices are SGD/MWh, times are instants (TIMESTAMPTZ).
-- Both tables cascade on delete so deleting a household or appliance (CSDT4-62) still works.

CREATE TABLE recommendation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id BIGINT NOT NULL REFERENCES household (id) ON DELETE CASCADE,
    appliance_id BIGINT NOT NULL REFERENCES appliance (id) ON DELETE CASCADE,
    kind VARCHAR(30) NOT NULL CHECK (kind IN ('SHIFT_START')),
    suggested_start TIMESTAMPTZ NOT NULL,
    usual_start TIMESTAMPTZ NOT NULL,
    -- Estimated cost of one run at each time, and the difference, from the forecast used.
    suggested_cost NUMERIC(12, 4) NOT NULL,
    usual_cost NUMERIC(12, 4) NOT NULL,
    est_saving NUMERIC(12, 4) NOT NULL CHECK (est_saving > 0),
    reason VARCHAR(500) NOT NULL,
    -- DEMO_FORECAST or F3_FORECAST, so a demo suggestion can never pass as a real prediction.
    forecast_source VARCHAR(30) NOT NULL CHECK (forecast_source IN ('DEMO_FORECAST', 'F3_FORECAST')),
    forecast_model VARCHAR(60),
    status VARCHAR(20) NOT NULL
        CHECK (status IN ('ACTIVE', 'ACCEPTED', 'DISMISSED', 'SUPERSEDED', 'EXPIRED')),
    -- Where the resident chose to run it: the suggestion, or their own override time.
    accepted_start TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    decided_at TIMESTAMPTZ,
    CONSTRAINT ck_recommendation_decided
        CHECK (status NOT IN ('ACCEPTED', 'DISMISSED') OR decided_at IS NOT NULL),
    CONSTRAINT ck_recommendation_accepted_start
        CHECK ((status = 'ACCEPTED') = (accepted_start IS NOT NULL))
);

CREATE INDEX idx_recommendation_household ON recommendation (household_id, status, suggested_start);

-- At most one open suggestion per appliance; a newer one supersedes the old one.
CREATE UNIQUE INDEX uq_recommendation_one_active
    ON recommendation (appliance_id) WHERE status = 'ACTIVE';

-- Every change of status is logged, including the resident's accept/dismiss decisions.
CREATE TABLE recommendation_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id BIGINT NOT NULL REFERENCES recommendation (id) ON DELETE CASCADE,
    event_type VARCHAR(20) NOT NULL
        CHECK (event_type IN ('CREATED', 'ACCEPTED', 'DISMISSED', 'SUPERSEDED', 'EXPIRED')),
    occurred_at TIMESTAMPTZ NOT NULL,
    -- For ACCEPTED: the start the resident agreed to (may be their override).
    start_at TIMESTAMPTZ,
    overridden BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_recommendation_event_recommendation
    ON recommendation_event (recommendation_id, occurred_at);
