CREATE TABLE market_price (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(40) NOT NULL,
    interval_start TIMESTAMPTZ NOT NULL,
    source_updated_at TIMESTAMPTZ NOT NULL,
    fetched_at TIMESTAMPTZ NOT NULL,
    usep_sgd_per_mwh NUMERIC(14, 4) NOT NULL,
    forecast_demand_mw NUMERIC(14, 3) NOT NULL,
    vcp_sgd_per_mwh NUMERIC(14, 4),
    CONSTRAINT uq_market_price_source_interval UNIQUE (source, interval_start)
);

CREATE INDEX idx_market_price_interval_start
    ON market_price (interval_start DESC);

CREATE TABLE ingestion_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(20) NOT NULL,
    source_updated_at TIMESTAMPTZ,
    error_message VARCHAR(1000)
);

CREATE INDEX idx_ingestion_run_started_at
    ON ingestion_run (started_at DESC, id DESC);
