CREATE TABLE market_observation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_updated_at TIMESTAMPTZ NOT NULL,
    first_collected_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    source_age_seconds_at_collection DOUBLE PRECISION NOT NULL,
    feed_stale_at_collection BOOLEAN NOT NULL,
    payload JSONB NOT NULL UNIQUE
);

CREATE TABLE weather_observation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issued_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    valid_start TIMESTAMPTZ NOT NULL,
    valid_end TIMESTAMPTZ NOT NULL CHECK (valid_end > valid_start),
    first_collected_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    item JSONB NOT NULL,
    UNIQUE (issued_at, updated_at)
);
CREATE INDEX idx_weather_match ON weather_observation (updated_at DESC, issued_at DESC);

-- Display timestamps as ISO-8601 Singapore time, matching the demo CSV.
CREATE VIEW combined_observations AS
SELECT
    encode(sha256(convert_to(p.payload::text, 'UTF8')), 'hex') AS record_id,
    to_char(p.source_updated_at AT TIME ZONE 'Asia/Singapore', 'YYYY-MM-DD"T"HH24:MI:SS') || '+08:00' AS source_updated_sgt,
    extract(epoch FROM p.source_updated_at)::bigint AS source_updated_unix,
    to_char(p.first_collected_at AT TIME ZONE 'Asia/Singapore', 'YYYY-MM-DD"T"HH24:MI:SS') || '+08:00' AS first_collected_sgt,
    to_char(p.last_seen_at AT TIME ZONE 'Asia/Singapore', 'YYYY-MM-DD"T"HH24:MI:SS') || '+08:00' AS last_seen_sgt,
    p.source_age_seconds_at_collection,
    p.feed_stale_at_collection,
    (p.payload->>'usep')::numeric AS usep_sgd_per_mwh,
    (p.payload->>'demand')::numeric AS demand_forecast_mw,
    (p.payload->>'vcp')::numeric AS vcp_sgd_per_mwh,
    CASE WHEN w.id IS NULL THEN 'no_matching_weather' ELSE 'matched_as_of_source_update' END AS weather_match_status,
    to_char(w.issued_at AT TIME ZONE 'Asia/Singapore', 'YYYY-MM-DD"T"HH24:MI:SS') || '+08:00' AS weather_issued_sgt,
    to_char(w.updated_at AT TIME ZONE 'Asia/Singapore', 'YYYY-MM-DD"T"HH24:MI:SS') || '+08:00' AS weather_updated_sgt,
    to_char(w.valid_start AT TIME ZONE 'Asia/Singapore', 'YYYY-MM-DD"T"HH24:MI:SS') || '+08:00' AS weather_valid_start_sgt,
    to_char(w.valid_end AT TIME ZONE 'Asia/Singapore', 'YYYY-MM-DD"T"HH24:MI:SS') || '+08:00' AS weather_valid_end_sgt,
    p.id AS price_response_id,
    w.id AS weather_response_id,
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Ang Mo Kio' LIMIT 1) AS "weather_Ang_Mo_Kio",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Bedok' LIMIT 1) AS "weather_Bedok",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Bishan' LIMIT 1) AS "weather_Bishan",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Boon Lay' LIMIT 1) AS "weather_Boon_Lay",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Bukit Batok' LIMIT 1) AS "weather_Bukit_Batok",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Bukit Merah' LIMIT 1) AS "weather_Bukit_Merah",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Bukit Panjang' LIMIT 1) AS "weather_Bukit_Panjang",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Bukit Timah' LIMIT 1) AS "weather_Bukit_Timah",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Central Water Catchment' LIMIT 1) AS "weather_Central_Water_Catchment",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Changi' LIMIT 1) AS "weather_Changi",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Choa Chu Kang' LIMIT 1) AS "weather_Choa_Chu_Kang",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'City' LIMIT 1) AS "weather_City",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Clementi' LIMIT 1) AS "weather_Clementi",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Geylang' LIMIT 1) AS "weather_Geylang",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Hougang' LIMIT 1) AS "weather_Hougang",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Jalan Bahar' LIMIT 1) AS "weather_Jalan_Bahar",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Jurong East' LIMIT 1) AS "weather_Jurong_East",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Jurong Island' LIMIT 1) AS "weather_Jurong_Island",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Jurong West' LIMIT 1) AS "weather_Jurong_West",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Kallang' LIMIT 1) AS "weather_Kallang",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Lim Chu Kang' LIMIT 1) AS "weather_Lim_Chu_Kang",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Mandai' LIMIT 1) AS "weather_Mandai",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Marine Parade' LIMIT 1) AS "weather_Marine_Parade",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Novena' LIMIT 1) AS "weather_Novena",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Pasir Ris' LIMIT 1) AS "weather_Pasir_Ris",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Paya Lebar' LIMIT 1) AS "weather_Paya_Lebar",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Pioneer' LIMIT 1) AS "weather_Pioneer",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Pulau Tekong' LIMIT 1) AS "weather_Pulau_Tekong",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Pulau Ubin' LIMIT 1) AS "weather_Pulau_Ubin",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Punggol' LIMIT 1) AS "weather_Punggol",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Queenstown' LIMIT 1) AS "weather_Queenstown",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Seletar' LIMIT 1) AS "weather_Seletar",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Sembawang' LIMIT 1) AS "weather_Sembawang",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Sengkang' LIMIT 1) AS "weather_Sengkang",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Sentosa' LIMIT 1) AS "weather_Sentosa",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Serangoon' LIMIT 1) AS "weather_Serangoon",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Southern Islands' LIMIT 1) AS "weather_Southern_Islands",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Sungei Kadut' LIMIT 1) AS "weather_Sungei_Kadut",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Tampines' LIMIT 1) AS "weather_Tampines",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Tanglin' LIMIT 1) AS "weather_Tanglin",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Tengah' LIMIT 1) AS "weather_Tengah",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Toa Payoh' LIMIT 1) AS "weather_Toa_Payoh",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Tuas' LIMIT 1) AS "weather_Tuas",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Western Islands' LIMIT 1) AS "weather_Western_Islands",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Western Water Catchment' LIMIT 1) AS "weather_Western_Water_Catchment",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Woodlands' LIMIT 1) AS "weather_Woodlands",
    (SELECT f->>'forecast' FROM jsonb_array_elements(w.item->'forecasts') f
     WHERE f->>'area' = 'Yishun' LIMIT 1) AS "weather_Yishun",
    p.payload AS price_payload_json,
    w.item AS weather_item_json
FROM market_observation p
LEFT JOIN LATERAL (
    SELECT * FROM weather_observation w
    WHERE w.issued_at <= p.source_updated_at AND w.updated_at <= p.source_updated_at
      AND w.valid_start <= p.source_updated_at AND w.valid_end > p.source_updated_at
    ORDER BY w.updated_at DESC, w.issued_at DESC, w.id DESC
    LIMIT 1
) w ON true;
