-- F2 (CSDT4-14, CSDT4-15): households, their electricity plan, and their appliances.
-- Units: power in kW (never kWh), run time in minutes, fixed tariff in cents per kWh.
-- Times of day are Singapore local wall-clock times (TIME without zone).

CREATE TABLE household (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    dwelling_type VARCHAR(40) NOT NULL,
    occupants INT NOT NULL CHECK (occupants BETWEEN 1 AND 20),
    plan_type VARCHAR(20) NOT NULL CHECK (plan_type IN ('FIXED', 'PRICE_LINKED')),
    fixed_rate_cents_per_kwh NUMERIC(8, 4),
    -- Filled in by the load-archetype work (CSDT4-29); no foreign key until that table exists.
    archetype_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_household_fixed_rate
        CHECK (plan_type <> 'FIXED'
               OR (fixed_rate_cents_per_kwh IS NOT NULL AND fixed_rate_cents_per_kwh > 0))
);

CREATE TABLE appliance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id BIGINT NOT NULL REFERENCES household (id) ON DELETE CASCADE,
    name VARCHAR(80) NOT NULL,
    type VARCHAR(30) NOT NULL,
    power_kw NUMERIC(8, 3) NOT NULL CHECK (power_kw > 0),
    run_minutes INT NOT NULL CHECK (run_minutes BETWEEN 1 AND 1440),
    flexibility VARCHAR(20) NOT NULL
        CHECK (flexibility IN ('FLEXIBLE', 'FIXED', 'NOT_FLEXIBLE')),
    earliest_start TIME,
    must_finish_by TIME,
    usual_start TIME,
    runs_per_week INT NOT NULL DEFAULT 7 CHECK (runs_per_week BETWEEN 0 AND 70),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    notes VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_appliance_household ON appliance (household_id, id);
