-- F2 (CSDT4-29): household load archetypes calibrated to EMA's published averages.
-- monthly_kwh = average monthly household electricity consumption in 2024, by dwelling type,
-- from MSE's written reply to a parliamentary question (24 Sep 2025), which cites EMA data.
-- These are MODELLED figures, not metered data. The daily shape lives in DailyLoadShape.java.

CREATE TABLE load_archetype (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL UNIQUE,
    dwelling_type VARCHAR(40) NOT NULL UNIQUE,
    label VARCHAR(80) NOT NULL,
    monthly_kwh NUMERIC(8, 1) NOT NULL CHECK (monthly_kwh > 0),
    -- A weekend day uses this many times the energy of a weekday (assumption, not EMA data).
    weekend_factor NUMERIC(4, 2) NOT NULL DEFAULT 1.10 CHECK (weekend_factor > 0),
    source VARCHAR(300) NOT NULL
);

INSERT INTO load_archetype (code, dwelling_type, label, monthly_kwh, source) VALUES
    ('HDB_1_2_ROOM', 'HDB_1_2_ROOM', '1–2 room HDB flat', 175.7,
        'EMA 2024 average via MSE written PQ reply, 24 Sep 2025'),
    ('HDB_3_ROOM', 'HDB_3_ROOM', '3-room HDB flat', 276.1,
        'EMA 2024 average via MSE written PQ reply, 24 Sep 2025'),
    ('HDB_4_ROOM', 'HDB_4_ROOM', '4-room HDB flat', 380.7,
        'EMA 2024 average via MSE written PQ reply, 24 Sep 2025'),
    ('HDB_5_ROOM_EXECUTIVE', 'HDB_5_ROOM_EXECUTIVE', '5-room / Executive HDB flat', 464.0,
        'EMA 2024 average via MSE written PQ reply, 24 Sep 2025'),
    ('PRIVATE_APARTMENT_CONDO', 'PRIVATE_APARTMENT_CONDO', 'Private apartment / condominium', 522.0,
        'EMA 2024 average via MSE written PQ reply, 24 Sep 2025'),
    ('LANDED', 'LANDED', 'Landed property', 1208.2,
        'EMA 2024 average via MSE written PQ reply, 24 Sep 2025');

ALTER TABLE household
    ADD CONSTRAINT fk_household_archetype
    FOREIGN KEY (archetype_id) REFERENCES load_archetype (id);

-- Give existing households the archetype that matches their home type.
UPDATE household h
SET archetype_id = a.id
FROM load_archetype a
WHERE a.dwelling_type = h.dwelling_type
  AND h.archetype_id IS NULL;
